package models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "candidateForm")
@DynamoDBDocument
public class CandidateForm  {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	private String candidateId;
	
	@DynamoDBAttribute
	private String testStatus;
	
	@DynamoDBAttribute
	private String testResult;
	
	@DynamoDBAttribute
	private Test testForm;

	
	public CandidateForm()	{
		
	}
	
	public CandidateForm(String id, String candidateId, String testStatus, String testResult, Test testForm) {
		this.id = id;
		this.candidateId = candidateId;
		this.testStatus = testStatus;
		this.testResult = testResult;
		this.testForm = testForm;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCandidateId() {
		return candidateId;
	}

	public void setCandidateId(String candidateId) {
		this.candidateId = candidateId;
	}

	public String getTestStatus() {
		return testStatus;
	}

	public void setTestStatus(String testStatus) {
		this.testStatus = testStatus;
	}

	public String getTestResult() {
		return testResult;
	}

	public void setTestResult(String testResult) {
		this.testResult = testResult;
	}

	public Test getTestForm() {
		return testForm;
	}

	public void setTestForm(Test testForm) {
		this.testForm = testForm;
	}
	
	
}
