package models;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Questions_bez_stringow")
@DynamoDBDocument
public class Question  {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	private String type;
	
	@DynamoDBAttribute
	private String question;
	
	@DynamoDBAttribute
	private List<Answer> answer;
	
	
	public Question()	{
		
	}
	
	public Question (String id, String type, String question, List<Answer> answer)	{
		this.id = id;
		this.type = type;
		this.question = question;
		this.answer = answer;
	}
	
	public String getId()	{
		return id;
	}
	
	public void setId(String id)	{
		this.id = id;
	}
	
	public String getType()	{
		return type;
	}
	
	public void setType(String type)	{
		this.type = type;
	}
	
	public String getQuestion()	{
		return question;
	}
	
	public void setQuestion(String question)	{
		this.question = question;
	}
	
	public List<Answer> getAnswer()	{
		return answer;
	}
	
	public void setAnswer(List<Answer> answer)	{
		this.answer = answer;
	}
}
